#!/usr/bin/env node
// 多言語の生成（トップページ・言語メニュー・hreflang）。言語一覧の正本は tools/i18n/pages.js。
//   1. index.html（日本語＝正本）と法務ページの hreflang ブロックを、存在する言語ぶんに書き換える
//   2. 各言語のトップページ <dir>/index.html を生成（訳は tools/i18n/<言語>.js の pairs＝原文→訳）
//      原文が見つからない／件数が合わない／日本語が残る場合はビルドを止める
//   3. 言語メニュー・初回の言語案内・前回選んだ言語への移動を行う lang.js を書き出す
// 使い方: node tools/build-i18n.js
const fs = require("fs"), path = require("path");
const ROOT = path.join(__dirname, "..");
const BASE = "https://nobukuru114.github.io/hotel-price-world";
const P = require("./i18n/pages.js"), KEYS = Object.keys(P), XDEFAULT = "en";
const { localNames } = require("./i18n/names.js");
const count = (h, n) => h.split(n).length - 1;
const TOPS = KEYS.filter(k => k === "ja" || fs.existsSync(path.join(__dirname, "i18n", k + ".js")));   // トップページのある言語
const LEGAL = ["disclaimer.html", "privacy.html", "about.html"];
let failed = false;

// ---- 1. hreflang ブロック ----
const block = (langs, page) => "<!-- hreflang:start (generated by tools/build-i18n.js from tools/i18n/pages.js) -->\n"
  + langs.map(k => `<link rel="alternate" hreflang="${P[k].htmlLang}" href="${BASE}/${P[k].dir}${page}">`).join("\n")
  + (langs.includes(XDEFAULT) ? `\n<link rel="alternate" hreflang="x-default" href="${BASE}/${P[XDEFAULT].dir}${page}">` : "") + "\n<!-- hreflang:end -->";
const BLOCK_RE = /<!-- hreflang:start[^>]*-->[\s\S]*?<!-- hreflang:end -->/;
function setBlock(file, html){ const s = fs.readFileSync(file, "utf8"); if(!BLOCK_RE.test(s)) return false;
  const t = s.replace(BLOCK_RE, html); if(t !== s) fs.writeFileSync(file, t); return true; }
setBlock(path.join(ROOT, "index.html"), block(TOPS, ""));
LEGAL.forEach(page => { const langs = KEYS.filter(k => fs.existsSync(path.join(ROOT, P[k].dir, page)));
  langs.forEach(k => setBlock(path.join(ROOT, P[k].dir, page), block(langs, page))); });

// ---- 2. 各言語のトップページ ----
const src = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
const line = k => { const m = src.match(new RegExp("^const " + k + " = (.*);$", "m")); if(!m) throw new Error(k + " not found"); return m; };
const DATA = JSON.parse(line("DATA")[1]), CJ = JSON.parse(line("CJ")[1]);
TOPS.filter(k => k !== "ja").forEach(code => {
  const L = require(`./i18n/${code}.js`), M = P[code];
  let out = src;
  const miss = [];
  L.pairs.forEach(([from, to, n]) => {
    const want = n || 1, got = count(out, from);
    if(got !== want){ miss.push(`${got}/${want}: ${from.slice(0, 60)}`); return; }
    out = out.split(from).join(to);
  });
  if(miss.length){
    console.error(`[${code}] 訳の対応が取れない原文が ${miss.length} 件あります（index.html を直したら tools/i18n/${code}.js も直してください）:`);
    miss.forEach(m => console.error("  " + m)); failed = true; return;
  }
  // 既定の表示通貨（正本: pages.js の defCur）
  if(count(out, 'let curCode = "JPY";') !== 1) throw new Error("curCode not found");
  out = out.replace('let curCode = "JPY";', "let curCode = " + JSON.stringify(M.defCur) + ";");
  // OGP 画像と代替テキスト
  out = out.replace("/og/ja.png", `/og/${code}.png`).replace(/<meta property="og:image:alt" content="[^"]*">/, `<meta property="og:image:alt" content="${M.og.alt}">`);
  // 通貨名
  const cm = out.match(/^const CURS = (.*);$/m); if(!cm) throw new Error("CURS not found");
  const CURS = eval("(" + cm[1] + ")");
  out = out.replace(cm[0], "const CURS = " + JSON.stringify(Object.fromEntries(Object.entries(CURS).map(([k, v]) => [k, [v[0], L.currencyNames[k] || k]]))) + ";");
  // 都市名・国名（ja・en 以外）: 訳の jname / cname が参照する LN / LC を CJ の直後に置く
  if(code !== "en"){
    const { LN, LC, missing } = localNames(code, M.htmlLang, DATA, CJ);
    if(missing.length) console.warn(`[${code}] 都市名の訳が無い都市 ${missing.length}（英語名で表示）: ${missing.slice(0, 5).join(", ")}…`);
    const cj = out.match(/^const CJ = .*;$/m)[0];
    out = out.replace(cj, cj + "\nconst LN = " + JSON.stringify(LN) + ";\nconst LC = " + JSON.stringify(LC) + ";");
  }
  out = out.replace('<script src="lang.js" defer></script>', '<script src="../lang.js" defer></script>');
  const dir = path.join(ROOT, M.dir); fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "index.html"), out);
  // 残っている日本語の検査（データ・コメントは除く）
  const DATA_RE = /^const (DATA|CJ|SLUG|CSLUG|RATES|CURS|LN|LC) = /, J = /[぀-ヿ一-鿿]/;
  const cjk = /^(zh|ja)/.test(M.htmlLang);                            // 中国語は漢字を使うので仮名だけで判定
  const JJ = cjk ? /[぀-ヿ]/ : J;
  const left = out.split("\n").map((l, i) => [i + 1, l]).filter(([, l]) => !DATA_RE.test(l))
    .map(([i, l]) => [i, l.replace(/\/\/.*$/, "").replace(/\/\*.*?\*\//g, "")])
    .filter(([, l]) => JJ.test(l)).filter(([, l]) => !/日本語|ja-JP|hreflang="ja"|lang="ja"/.test(l));
  console.log(`${M.dir}index.html: ${(out.length / 1024 | 0)}KB / 未訳の日本語行 ${left.length}`);
  left.slice(0, 20).forEach(([i, l]) => console.log("  L" + i + " " + l.trim().slice(0, 100)));
  if(left.length) failed = true;
});

// ---- 3. lang.js ----
const LS = KEYS.map(k => ({ k, h: P[k].htmlLang, d: P[k].dir, l: P[k].label, m: P[k].langMsg, t: TOPS.includes(k) ? 1 : 0 }));
fs.writeFileSync(path.join(ROOT, "lang.js"), `// 生成ファイル（tools/build-i18n.js が tools/i18n/pages.js から作る）。直接編集しない。
// 言語メニュー／前回選んだ言語への移動／初回だけブラウザ言語に合わせた案内バー（強制リダイレクトはしない）。
(function(){
  var LS = ${JSON.stringify(LS)};
  var s = document.currentScript, base = s ? s.src.replace(/lang\\.js(\\?.*)?$/, "") : "", here = null, i;
  for(i = 0; i < LS.length; i++) if(LS[i].h === document.documentElement.lang) here = LS[i];
  if(!here || !base) return;
  var rest = location.href.split("#")[0].split("?")[0];
  rest = rest.indexOf(base) === 0 ? rest.slice(base.length) : "";
  if(here.d && rest.indexOf(here.d) === 0) rest = rest.slice(here.d.length);
  var avail = []; for(i = 0; i < LS.length; i++) if(LS[i].t || rest !== "" && rest !== "index.html") avail.push(LS[i]);
  function url(x){ return base + x.d + rest + location.hash; }
  function save(k){ try{ localStorage.setItem("lang", k); }catch(e){} }
  var sel = document.createElement("select");
  sel.className = "cursel langsel"; sel.setAttribute("aria-label", "Language / 言語");
  sel.innerHTML = avail.map(function(x){ return '<option value="' + x.k + '" lang="' + x.h + '"' + (x === here ? " selected" : "") + ">" + x.l + "</option>"; }).join("");
  sel.addEventListener("change", function(){ for(var j = 0; j < avail.length; j++) if(avail[j].k === sel.value){ save(avail[j].k); location.href = url(avail[j]); } });
  var slot = document.getElementById("langslot");
  if(slot) slot.parentNode.replaceChild(sel, slot); else { var tb = document.querySelector(".tbwrap"); if(tb) tb.appendChild(sel); }
  var saved = null; try{ saved = localStorage.getItem("lang"); }catch(e){}
  if(saved && saved !== here.k){ for(i = 0; i < avail.length; i++) if(avail[i].k === saved){ location.replace(url(avail[i])); return; } }
  if(saved) return;
  function find(h){ for(var j = 0; j < avail.length; j++) if(avail[j].h.toLowerCase() === h.toLowerCase()) return avail[j]; return null; }
  function match(p){ var pr = p.split("-")[0];
    if(pr === "zh") return find(/-(tw|hk|mo|hant)/.test(p) ? "zh-Hant" : "zh-Hans");
    if(pr === "pt") return find("pt-BR");
    for(var j = 0; j < avail.length; j++) if(avail[j].h.toLowerCase().split("-")[0] === pr) return avail[j]; return null; }
  var pref = navigator.languages || [navigator.language || ""], best = null;
  for(i = 0; i < pref.length && !best; i++) best = match(String(pref[i]).toLowerCase());
  if(!best || best === here) return;
  var bar = document.createElement("div"); bar.className = "langbar"; bar.lang = best.h;
  bar.innerHTML = '<div class="wrap"><span>' + best.m + '</span> <a href="' + url(best) + '" hreflang="' + best.h + '">' + best.l + ' →</a><button type="button" aria-label="close">×</button></div>';
  bar.querySelector("a").addEventListener("click", function(){ save(best.k); });
  bar.querySelector("button").addEventListener("click", function(){ save(here.k); bar.parentNode.removeChild(bar); });
  var anchor = document.querySelector(".hero") || document.querySelector(".wrap");
  if(anchor) anchor.parentNode.insertBefore(bar, anchor);
})();
`);
console.log(`lang.js: ${KEYS.length}言語（トップあり ${TOPS.length}）`);
if(failed) process.exitCode = 1;
